### ISSUE TITLE
Dot product explained as matrix multiplication.

### ISSUE THREAD

**Issue by SergiiKashubin** [frnsys/ai_notes#1]
Hi Francis,
I am not sure where it is best to put it in the doc if at all, but dot product can be easily understood in terms of matrix multiplication: _a_ · _b_ is the same as _a_<sup>T</sup>_b_.  

This helps while learning linear algebra as one does not need to remember dot product as a separate concept anymore and can easily distinguish it from the outer product _ab_<sup>T</sup>. 

You use the same notation for both dot and outer product in the notes, so I think it is worth to mention how you can easily make a distinction this way.

**Comment by frnsys** [comment]
thank you for bringing this up, I'm clarifying the notation and adding the equivalent matrix multiplications.
