### ISSUE TITLE
fraction typo?

### ISSUE THREAD

**Issue by andrewjtimmons** [frnsys/ai_notes#3]
Hey Frnsys,

I was reading over the HTML version for the first time today.  It is really great. Looking forward to reading the rest this week.

I think there is a typo on this page
http://frnsys.com/ai_notes/foundations/probability.html 

If you ctrl+f "So the following probability properties of yellow should be straightforward:"
Below it is the line 
P(yellow) = 6/10 = 1/10

I think it should be 
P(yellow) = 6/60 = 1/10

Thanks so much for making this and sharing.

Cheers,
Andy

**Comment by frnsys** [comment]
oops I was not getting notifications for issues, so I'm just seeing this now. will be fixed in a moment :)
